services:
  liblib:
    build: .
    volumes:
      - type: bind
        source: ./env/
        target: /opt/liblib/env/
        read_only: true
      - type: bind
        source: ./output/
        target: /opt/liblib/output/
        read_only: false
    environment:
      - FILE_ENV=${FILE_ENV}
